v0: 80.0
V_list: [40.0,60.0, 80.0]
brake_types:
  - name: FSB
    source: kinematic
  - name: EB
    source: kinematic
  - name: holding
    source: ratio_of_FSB
    ratio: 0.5
  - name: jerk
    source: ratio_of_FSB
    ratio: 0.2
requirement:
  FSB:
    mode: a_mean
    value: 1.0
  EB:
    mode: distance
    value: 205.0
response_time:
  FSB:
    t1: 0.4
    impulse_rate: 0.75
  EB:
    t1: 0.3
    t2: 1.2
load_groups: [AW0, AW2, AW3]
controller_type: bogie
n_bogies_by_controller: 1
n_springs_by_controller: 2
n_cylinders_by_controller: 4
allocation_strategy: equal_wear
vehicle_config:
  bogies:
    - name: trailer_bogie_1
      bogie_type: trailer_bogie
    - name: trailer_bogie_2
      bogie_type: trailer_bogie
    - name: powered_bogie_3
      bogie_type: powered_bogie
    - name: powered_bogie_4
      bogie_type: powered_bogie
    - name: powered_bogie_5
      bogie_type: powered_bogie
    - name: powered_bogie_6
      bogie_type: powered_bogie
mass_params:
  powered_bogie:
    mass_static:
      AW0: 15.83
      AW2: 23.33
      AW3: 26.37
    bogie_weight: 6.3
    rotational_mass_factor: 0.1
  trailer_bogie:
    mass_static:
      AW0: 15.37
      AW2: 22.27
      AW3: 25.18
    bogie_weight: 4.1
    rotational_mass_factor: 0.05
air_spring:
  powered_bogie:
    mode: explicit_linear
    airspring_k: 43.69
    airspring_b: 4.13
  trailer_bogie:
    mode: explicit_linear
    airspring_k: 43.69
    airspring_b: 4.13
mech_params:
  cylinder_type: tread_cylinder
  Sc: 0.0248
  xi: 0.29
  Li: 3.4
  eta_i: 0.95
  Lo: 1.0
  eta_o: 1.0
  Fs1: 1.0
  Fs2: 0.25
pressure_calibration:
  enabled: true
  service_brake:
    BCP0: 25.0
    point_pair_mode: aw3_aw2
    points:
      - load_group: AW2
        brake_type: FSB
        k_for_code: 1080.0
      - load_group: AW3
        brake_type: FSB
        k_for_code: 1123.0
  emergency_brake:
    BCP0: 25.0
    point_pair_mode: aw3_aw0
    points:
      - load_group: AW0
        brake_type: EB
        k_for_code: 1014.0
      - load_group: AW3
        brake_type: EB
        k_for_code: 1204.0
parking_brake_check:
  enabled: true
  required_safety_margin: 1.2
  static_friction_coefficient: 0.35
  n_parking_cylinders_by_car: 4
  cylinder:
    Fp: 7.4
    Fs1: 1.0
    Fs2: 0.25
    Lpi: 3.4
    eta_pi: 0.95
    Lo: 1.0
    eta_o: 1.0
  environment:
    wind_speed_max: 29.7
    wind_resistance_coefficient: 0.0037
    grade_by_load_group:
      AW0: 40.0
      AW3: 35.0
adhesion:
  mu_limit: 0.15
electric_brake:
  enabled: false
  force_scope: train_total
  characteristic_points: []
EB_limit_min: 150.0
